### PR TITLE
Add icon

### PR DESCRIPTION
**Pull request by chrismwendt**
Similar to https://github.com/sourcegraph/sourcegraph-typescript/pull/230

### CODE REVIEW

**Comment by felixfbecker** [comment]
Does this need to be square?

**Comment by chrismwendt** [comment]
Heh, yup

image

**Comment by felixfbecker** [comment]
Perhaps the webapp CSS should also be fixed so this can't happen

**Comment by chrismwendt** [comment]
:+1: changing webapp CSS in https://github.com/sourcegraph/sourcegraph/pull/5161

**Comment by chrismwendt** [comment]
Squared up the icon so it doesn't look stretched between now and when https://github.com/sourcegraph/sourcegraph/pull/5161 is merged.

I'll also make sure other icons I add are square because customer instances don't have https://github.com/sourcegraph/sourcegraph/pull/5161 yet.

**Comment by felixfbecker** [comment]
Good thinking!

**Pull request merged**
